apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-crash-notifier
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: operator-crash-notifier
  template:
    metadata:
      labels:
        app: operator-crash-notifier
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | default "INFO" }}
